# ==================
# Project Details
# ==================
name: "macros_sql"
config-version: 2
require-dbt-version:
- ">=1.0.0"
- "<2.0.0"
version: "0.0.1"
profile: "prophecy-default"

# ==================
# File Path Configs
# ==================
model-paths:
- "models"
- "prophecy-sources"
macro-paths:
- "macros"
